# Generated by Django 5.1.1 on 2024-10-06 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="redactor",
            options={"verbose_name": "publisher", "verbose_name_plural": "publishers"},
        ),
    ]
